version: '3.7'

x-healthcheck:
  &default-healthcheck
  interval: "5s"
  timeout: "1s"
  retries: 3
  start_period: "20s"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  fluentd:
    image: sindan-fluentd:v1.6-1
    hostname: sindan-fluentd
    restart: always
    depends_on:
      - infuxdb
    ports:
      - "8080:8080"
      - "8888:8888"
    healthcheck:
      << : *default-healthcheck
      test: curl -f http://127.0.0.1:8080 || exit 1
    logging: *default-logging
    volumes:
      - .fluent.conf:/fluentd/etc/fluent.conf
      - fluentd-data:/fluentd/log
    labels:
      com.sindan-net.description: "Receive logs from sindan-clients and forward them to Python via HTTP"

  influxdb:
    image: quay.io/influxdb/influxdb:2.0.0-alpha
    hostname: sindan-influxdb
    restart: always
    ports:
      - '8083:8083'
      - '8086:8086'
      - '8090:8090'
      - '9999:9999'
    command: --reporting-disabled
    volumes:
      - 'influxdb-data:/var/lib/influxdb'

volumes:
  fluentd-data:
  influxdb-data:
